version: '3.8'

services:
  mysql-server:
    image: mysql:8
    container_name: botbinance-mysql-server
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev_db
    networks:
      - app-network
  #node-server:


networks:
  app-network:
    driver: bridge
    name: app-network
